In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__


'2.15.0'

In [ ]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]
 [  26.27   59.44 1012.23   58.77]
 [  15.89   43.96 1014.02   75.24]
 [   9.48   44.71 1019.12   66.43]
 [  14.64   45.   1021.78   41.25]
 [  11.74   43.56 1015.14   70.72]
 [  17.99   43.72 1008.64   75.04]
 [  20.14   46.93 1014.66   64.22]
 [  24.34   73.5  1011.31   84.15]
 [  25.71   58.59 1012.77   61.83]
 [  26.19   69.34 1009.48   87.59]
 [  21.42   43.79 1015.76   43.08]
 [  18.21   45.   1022.86   48.84]
 [  11.04   41.74 1022.6    77.51]
 [  14.45   52.75 1023.97   63.59]
 [  13.97   38.47 1015.15   55.28]
 [  17.76   42.42 1009.09   66.26]
 [   5.41   40.07 1019.16   64.77]
 [   7.76   42.28 1008.52   83.31]
 [  27.23   63.9  1014.3    47.19]
 [  27.36   48.6  1003.18   54.93]
 [  27.47   70.72 1009.97   74.62]
 [  14.6    39.31 1011.11   72.52]
 [   7.91   39.96 1023.57   88.44]
 [   5.81   35.79 10

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 204601.0625
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 192688.5156
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 147772.7969
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 75245.3203
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 29323.2031
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 17481.0000
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 13583.1953
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 10362.2275
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 7584.4321
Epoch 10/100
240/240 [==============================] - 1s 4ms/step - loss: 5351.2236
Epoch 11/100
240/240 [==============================] - 1s 4ms/step - loss: 3675.0959
Epoch 12/100
240/240 [==============================

In [ ]:
y_pred=ann.predict(X_test)
np.set_printoptions(threshold=np.inf, precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 2ms/step
[[435.27 431.23]
 [459.34 460.01]
 [463.64 461.14]
 [449.03 445.9 ]
 [458.47 451.29]
 [433.07 432.68]
 [473.69 477.5 ]
 [457.12 459.68]
 [475.12 477.5 ]
 [446.75 444.99]
 [442.3  444.37]
 [441.72 437.04]
 [445.16 442.34]
 [441.31 440.74]
 [438.63 436.55]
 [454.98 460.24]
 [445.3  448.66]
 [437.56 432.94]
 [451.81 452.82]
 [429.5  432.2 ]
 [436.43 430.96]
 [432.02 434.65]
 [475.11 473.56]
 [439.92 434.47]
 [448.25 450.92]
 [453.26 452.82]
 [482.35 485.94]
 [444.9  435.47]
 [452.48 448.96]
 [467.31 465.89]
 [477.8  482.52]
 [462.64 465.05]
 [474.73 475.51]
 [469.12 466.71]
 [470.28 472.42]
 [433.87 434.64]
 [467.09 467.97]
 [480.93 481.86]
 [433.99 437.72]
 [472.94 470.49]
 [446.53 449.04]
 [467.21 468.15]
 [457.54 457.94]
 [480.6  486.4 ]
 [444.12 443.52]
 [440.29 442.23]
 [433.49 430.61]
 [438.62 439.72]
 [471.01 467.98]
 [440.5  433.36]
 [458.49 448.74]
 [464.22 464.39]
 [441.   443.06]
 [468.24 470.23]
 [464.01 467.21]
 [443.7  449